services:
  app:
    container_name: lista-cha
    hostname: lista-cha
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8085:80"
    volumes:
      - ./keys:/app/keys:ro
    restart: unless-stopped
    networks:
      lista-cha-network:
        aliases:
          - lista-cha

networks:
  lista-cha-network:
    external: true
